// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SolutionSpecificVSSettings
{
    internal sealed partial class Vsix
    {
        public const string Id = "df2bbc04-f83d-4b8a-95f9-2612666a2757";
        public const string Name = "Solution Specific VSSettings";
        public const string Description = @"Imports a custom .vssettings on solution load.";
        public const string Language = "en-US";
        public const string Version = "1.0.0";
        public const string Author = "Iron Software";
        public const string Tags = "settings, solution, vssettings";
    }
}
