// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SolutionSpecificVSSettings
{
    internal sealed partial class Vsix
    {
        public const string Id = "7A7A54CF-455F-447C-9CF6-6E75075BCBD9";
        public const string Name = "Solution-specific VSSettings";
        public const string Description = @"Imports a custom .vssettings on solution load.";
        public const string Language = "en-US";
        public const string Version = "1.0.1";
        public const string Author = "Artem Koloskov";
        public const string Tags = "settings, solution, vssettings";
    }
}
